heat_template_version: ocata

description: Create networks to split out Overcloud traffic

resources:

  {%- for network in networks %}
    {%- if network.name != 'InternalApi' %}
  {{network.name}}Network:
    {%- else  %}
  InternalNetwork:
    {%- endif %}
    type: OS::TripleO::Network::{{network.name}}
  {%- endfor %}

  NetworkExtraConfig:
    type: OS::TripleO::Network::ExtraConfig
