heat_template_version: pike

description: >
  OpenStack Ceilometer Expirer service, disabled since pike

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

outputs:
  role_data:
    description: Role data for the disabled Ceilometer Expirer role.
    value:
      service_name: ceilometer_expirer
      upgrade_tasks:
        - name: Stop and disable ceilometer_expirer service on upgrade
          tags: step1
          service: name=openstack-ceilometer-expirer state=stopped enabled=no
