resource_registry:
{% for role in roles %}
  OS::TripleO::{{role.name}}::PreNetworkConfig: ../extraconfig/pre_network/host_config_and_reboot.yaml
{% endfor %}

#parameter_defaults:
  # Note: There are no global parameters which can be applied to all roles as
  # these configuration have to be specific to role.

  # Sample parameters for Compute and ComputeOvsDpdk roles
  #ComputeParameters:
    #KernelArgs: ""
    #TunedProfileName: ""
    #HostIsolatedCoreList: ""
  #ComputeOvsDpdkParameters:
    #KernelArgs: ""
    #TunedProfileName: ""
    #HostIsolatedCoreList: ""
