heat_template_version: ocata

description: >
  OpenStack containerized Ironic PXE service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerIronicPxeImage:
    description: image
    default: 'centos-binary-ironic-pxe:latest'
    type: string
  DockerIronicConfigImage:
    description: image
    default: 'centos-binary-ironic-pxe:latest'
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

outputs:
  role_data:
    description: Role data for the Ironic PXE role.
    value:
      service_name: ironic_pxe
      config_settings: {}
      step_config: ''
      service_config_settings: {}
      # BEGIN DOCKER SETTINGS
      docker_image: &ironic_pxe_image
        list_join:
          - '/'
          - [ {get_param: DockerNamespace}, {get_param: DockerIronicPxeImage} ]
      puppet_tags: ironic_config
      config_volume: ironic
      config_image:
        list_join:
          - '/'
          - [ {get_param: DockerNamespace}, {get_param: DockerIronicConfigImage} ]
      kolla_config:
         /var/lib/kolla/config_files/ironic_pxe_http.json:
           command: /usr/sbin/httpd -DFOREGROUND
           config_files:
           - dest: /etc/ironic/ironic.conf
             owner: ironic
             perm: '0640'
             source: /var/lib/kolla/config_files/src/etc/ironic/ironic.conf
           - dest: /etc/httpd/conf.d/10-ipxe_vhost.conf
             owner: root
             perm: '0644'
             source: /var/lib/kolla/config_files/src/etc/httpd/conf.d/10-ipxe_vhost.conf
           - dest: /etc/httpd/conf/httpd.conf
             owner: root
             perm: '0644'
             source: /var/lib/kolla/config_files/src/etc/httpd/conf/httpd.conf
           - dest: /etc/httpd/conf/ports.conf
             owner: root
             perm: '0644'
             source: /var/lib/kolla/config_files/src/etc/httpd/conf/ports.conf
         /var/lib/kolla/config_files/ironic_pxe_tftp.json:
           command: /usr/sbin/in.tftpd --foreground --user root --address 0.0.0.0:69 --map-file /var/lib/ironic/tftpboot/map-file /var/lib/ironic/tftpboot
           config_files:
           - dest: /etc/ironic/ironic.conf
             owner: ironic
             perm: '0640'
             source: /var/lib/kolla/config_files/src/etc/ironic/ironic.conf
           - dest: /var/lib/ironic/tftpboot/chain.c32
             owner: ironic
             perm: '0744'
             source: /var/lib/kolla/config_files/src/var/lib/ironic/tftpboot/chain.c32
           - dest: /var/lib/ironic/tftpboot/pxelinux.0
             owner: ironic
             perm: '0744'
             source: /var/lib/kolla/config_files/src/var/lib/ironic/tftpboot/pxelinux.0
           - dest: /var/lib/ironic/tftpboot/ipxe.efi
             owner: ironic
             perm: '0744'
             source: /var/lib/kolla/config_files/src/var/lib/ironic/tftpboot/ipxe.efi
           - dest: /var/lib/ironic/tftpboot/undionly.kpxe
             owner: ironic
             perm: '0744'
             source: /var/lib/kolla/config_files/src/var/lib/ironic/tftpboot/undionly.kpxe
           - dest: /var/lib/ironic/tftpboot/map-file
             owner: root
             perm: '0644'
             source: /var/lib/kolla/config_files/src/var/lib/ironic/tftpboot/map-file
      docker_config:
        step_4:
          ironic_pxe_tftp:
            start_order: 90
            image: *ironic_pxe_image
            net: host
            privileged: false
            restart: always
            volumes:
              - /var/lib/kolla/config_files/ironic_pxe_tftp.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/ironic/:/var/lib/kolla/config_files/src:ro
              - /etc/hosts:/etc/hosts:ro
              - /etc/localtime:/etc/localtime:ro
              - /dev/log:/dev/log
              - ironic:/var/lib/ironic/
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
          ironic_pxe_http:
            start_order: 91
            image: *ironic_pxe_image
            net: host
            privileged: false
            restart: always
            volumes:
              - /var/lib/kolla/config_files/ironic_pxe_http.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/ironic/:/var/lib/kolla/config_files/src:ro
              - /var/lib/config-data/ironic/etc/httpd/conf.modules.d:/etc/httpd/conf.modules.d:ro
              - /etc/hosts:/etc/hosts:ro
              - /etc/localtime:/etc/localtime:ro
              - ironic:/var/lib/ironic/
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
