heat_template_version: ocata

description: >
  OpenStack containerized Mistral Executor service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerMistralExecutorImage:
    description: image
    default: 'centos-binary-mistral-executor:latest'
    type: string
  DockerMistralConfigImage:
    description: image
    default: 'centos-binary-mistral-api:latest'
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json


resources:

  MistralBase:
    type: ../../puppet/services/mistral-executor.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}

outputs:
  role_data:
    description: Role data for the Mistral Executor role.
    value:
      service_name: {get_attr: [MistralBase, role_data, service_name]}
      config_settings:
        map_merge:
          - get_attr: [MistralBase, role_data, config_settings]
      step_config: {get_attr: [MistralBase, role_data, step_config]}
      service_config_settings: {get_attr: [MistralBase, role_data, service_config_settings]}
      # BEGIN DOCKER SETTINGS
      docker_image: &mistral_executor_image
        list_join:
          - '/'
          - [ {get_param: DockerNamespace}, {get_param: DockerMistralExecutorImage} ]
      puppet_tags: mistral_config
      config_volume: mistral
      config_image:
        list_join:
          - '/'
          - [ {get_param: DockerNamespace}, {get_param: DockerMistralConfigImage} ]
      kolla_config:
         /var/lib/kolla/config_files/mistral_executor.json:
           command: /usr/bin/mistral-server --config-file=/etc/mistral/mistral.conf --log-file=/var/log/mistral/executor.log --server=executor
           config_files:
           - dest: /etc/mistral/mistral.conf
             owner: mistral
             perm: '0640'
             source: /var/lib/kolla/config_files/src/etc/mistral/mistral.conf
      docker_config:
        step_4:
          mistral_executor:
            image: *mistral_executor_image
            net: host
            privileged: false
            restart: always
            volumes:
              - /run:/run
              - /var/lib/kolla/config_files/mistral_executor.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/mistral/:/var/lib/kolla/config_files/src:ro
              - /etc/hosts:/etc/hosts:ro
              - /etc/localtime:/etc/localtime:ro
              # FIXME: this is required in order for Nova cells
              # initialization workflows on the Undercloud. Need to
              # exclude this on the overcloud for security reasons.
              - /var/lib/config-data/nova/etc/nova:/etc/nova:ro
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
