heat_template_version: pike

description: >
  OpenStack containerized Nova Compute service

parameters:
  DockerNovaComputeImage:
    description: image
    type: string
  DockerNovaLibvirtConfigImage:
    description: The container image to use for the nova_libvirt config_volume
    type: string
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  ContainersCommon:
    type: ./containers-common.yaml

  NovaComputeBase:
    type: ../../puppet/services/nova-compute.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

outputs:
  role_data:
    description: Role data for the Nova Compute service.
    value:
      service_name: {get_attr: [NovaComputeBase, role_data, service_name]}
      config_settings:
        map_merge:
          - get_attr: [NovaComputeBase, role_data, config_settings]
          # FIXME: we need to disable migration for now as the
          # hieradata is common for all services, and this means nova
          # and nova_placement puppet runs also try to configure
          # libvirt, and they fail. We can remove this override when
          # we have hieradata separation between containers.
          - tripleo::profile::base::nova::manage_migration: false
      step_config: &step_config
        get_attr: [NovaComputeBase, role_data, step_config]
      puppet_config:
        config_volume: nova_libvirt
        puppet_tags: nova_config,nova_paste_api_ini
        step_config: *step_config
        config_image: {get_param: DockerNovaLibvirtConfigImage}
      kolla_config:
        /var/lib/kolla/config_files/nova_compute.json:
          command: /usr/bin/nova-compute --config-file /etc/nova/nova.conf --config-file /etc/nova/rootwrap.conf
          config_files:
            - source: "/var/lib/kolla/config_files/src/*"
              dest: "/"
              merge: true
              preserve_properties: true
          permissions:
            - path: /var/log/nova
              owner: nova:nova
              recurse: true
            - path: /var/lib/nova
              owner: nova:nova
              recurse: true
      docker_config:
        # FIXME: run discover hosts here
        step_4:
          nova_compute:
            image: &nova_compute_image {get_param: DockerNovaComputeImage}
            net: host
            privileged: true
            user: nova
            restart: always
            volumes:
              list_concat:
                - {get_attr: [ContainersCommon, volumes]}
                -
                  - /var/lib/kolla/config_files/nova_compute.json:/var/lib/kolla/config_files/config.json:ro
                  - /var/lib/config-data/puppet-generated/nova_libvirt/:/var/lib/kolla/config_files/src:ro
                  - /dev:/dev
                  - /etc/iscsi:/etc/iscsi
                  - /lib/modules:/lib/modules:ro
                  - /run:/run
                  - /var/lib/nova:/var/lib/nova
                  - /var/lib/libvirt:/var/lib/libvirt
                  - /var/log/containers/nova:/var/log/nova
            environment:
             - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      host_prep_tasks:
        - name: create persistent directories
          file:
            path: "{{ item }}"
            state: directory
          with_items:
            - /var/log/containers/nova
            - /var/lib/nova
            - /var/lib/libvirt
      upgrade_tasks:
        - name: Stop and disable nova-compute service
          tags: step2
          service: name=openstack-nova-compute state=stopped enabled=no
