heat_template_version: ocata

description: >
  OpenStack containerized Nova Ironic Compute service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerNovaComputeImage:
    description: image
    default: 'centos-binary-nova-compute-ironic:latest'
    type: string
  DockerNovaBaseImage:
    description: image
    default: 'centos-binary-nova-base:latest'
    type: string
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:


  NovaIronicBase:
    type: ../../puppet/services/nova-ironic.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Nova Compute service.
    value:
      service_name: {get_attr: [NovaIronicBase, role_data, service_name]}
      config_settings: {get_attr: [NovaIronicBase, role_data, config_settings]}
      step_config: {get_attr: [NovaIronicBase, role_data, step_config]}
      puppet_tags: nova_config,nova_paste_api_ini
      docker_image: &nova_ironic_image
        list_join:
        - '/'
        - [ {get_param: DockerNamespace}, {get_param: DockerNovaComputeImage} ]
      config_volume: nova
      config_image:
        list_join:
        - '/'
        - [ {get_param: DockerNamespace}, {get_param: DockerNovaBaseImage} ]
      kolla_config:
        /var/lib/kolla/config_files/nova_ironic.json:
           command: /usr/bin/nova-compute --config-file /etc/nova/nova.conf --config-file /etc/nova/rootwrap.conf
           config_files:
           - dest: /etc/nova/nova.conf
             owner: nova
             perm: '0600'
             source: /var/lib/kolla/config_files/src/etc/nova/nova.conf
           - dest: /etc/nova/rootwrap.conf
             owner: nova
             perm: '0600'
             source: /var/lib/kolla/config_files/src/etc/nova/rootwrap.conf
      docker_config:
        step_5:
          novacompute:
            image: *nova_ironic_image
            net: host
            privileged: true
            user: root
            restart: always
            volumes:
              - /var/lib/kolla/config_files/nova_ironic.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/nova:/var/lib/kolla/config_files/src:ro
              - /etc/localtime:/etc/localtime:ro
              - /run:/run
              - /dev:/dev
              - /etc/iscsi:/etc/iscsi
              - nova_compute:/var/lib/nova/
            environment:
             - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
