heat_template_version: ocata

description: >
  OpenStack containerized Nova Scheduler service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerNovaSchedulerImage:
    description: image
    default: 'centos-binary-nova-scheduler:latest'
    type: string
  DockerNovaBaseImage:
    description: image
    default: 'centos-binary-nova-base:latest'
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

resources:

  NovaSchedulerBase:
    type: ../../puppet/services/nova-scheduler.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}

outputs:
  role_data:
    description: Role data for the Nova Scheduler service.
    value:
      service_name: {get_attr: [NovaSchedulerBase, role_data, service_name]}
      config_settings: {get_attr: [NovaSchedulerBase, role_data, config_settings]}
      step_config: {get_attr: [NovaSchedulerBase, role_data, step_config]}
      service_config_settings: {get_attr: [NovaSchedulerBase, role_data, service_config_settings]}
      # BEGIN DOCKER SETTINGS
      docker_image: &nova_scheduler_image
        list_join:
          - '/'
          - [ {get_param: DockerNamespace}, {get_param: DockerNovaSchedulerImage} ]
      puppet_tags: nova_config
      config_volume: nova
      config_image:
        list_join:
        - '/'
        - [ {get_param: DockerNamespace}, {get_param: DockerNovaBaseImage} ]
      kolla_config:
         /var/lib/kolla/config_files/nova_scheduler.json:
           command: /usr/bin/nova-scheduler
           config_files:
           - dest: /etc/nova/nova.conf
             owner: nova
             perm: '0600'
             source: /var/lib/kolla/config_files/src/etc/nova/nova.conf
      docker_config:
        step_4:
          nova_scheduler:
            image: *nova_scheduler_image
            net: host
            privileged: false
            restart: always
            volumes:
              - /run:/run
              - /var/lib/kolla/config_files/nova_scheduler.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/nova/:/var/lib/kolla/config_files/src:ro
              - /etc/hosts:/etc/hosts:ro
              - /etc/localtime:/etc/localtime:ro
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
